### ISSUE TITLE
Verwijderen Building met Rooms

### ISSUE THREAD

**Issue by SandervDoorn** [ronaldvandijk/colloquiumapp#128]
Als ik een building verwijder waar rooms aangekoppeld zitten krijg ik een contraint error, dit moet of een waarschuwing worden dat er ook rooms verwijderd worden met dan de vraag de delete te forcen OF gewoon de delete doordouwen en rooms meenemen in deletion

**Comment by maantje** [comment]
@SandervDoorn Picking this up!
