### ISSUE TITLE
Commit 24 @Melle, IBM

### ISSUE THREAD

**Issue by SandervDoorn** [ronaldvandijk/colloquiumapp#27]
[Testreport Commit 24 Open.docx](https://github.com/ronaldvandijk/colloquiumapp/files/583292/Testreport.Commit.24.Open.docx)
Routing
Routing Admin/Themes is goed.
Functionaliteit
Alle functionaliteiten zijn prima:
-	Duplicate names zijn niet mogelijk
-	Aanmaken werkt
-	Updaten werkt
-	Verwijderen werkt
-	Na het verwijderen van een thema is het weer mogelijk de naam te gebruiken
Weergave
Ik mis nog de knop in het admin panel om bij het theme venster te komen. Is toch wel nuttig om te hebben.
Ik mis bij het create scherm nog een terugknop, stel dat ik toch niet wil createn, dan moet ik de URL editen om terug te gaan of browser terug doen. Voor netheid nog een vorige knop erbij zou mooi zijn. 
De talen lijken ook enigszins gemixt. Veel dingen in het engels en aantal in het nederlands, we gebruiken basetaal nederlands en vertalen het later. -> Kan punt zijn voor ATOS om dit in de HTML aan te passen?

**Comment by melledijkstra** [comment]
Knoppen om terug te gaan vanaf create view zit er nu in. Vertalingen ook in hele Thema gedeelte. Pull request is al gemerged

**Comment by SandervDoorn** [comment]
Basetaal is nog in het engels
[Testreport Commit 29 Open.docx](https://github.com/ronaldvandijk/colloquiumapp/files/583466/Testreport.Commit.29.Open.docx)
