### ISSUE TITLE
BaseTypeController verbied "php artisan route:list"

### ISSUE THREAD

**Issue by melledijkstra** [ronaldvandijk/colloquiumapp#33]
@sandervankasteel Success! ;p

the fix die we hadden gevonden:
`       $models = new $this->modelClass->all();

        $data = [
            'properties' => $this->properties,
            'data' => $models,
            'baseUrl' => $this->baseUrl,
            'controllerName' => $this->getClassNameController()
        ];`

**in plaats van:**

` 'data' => $this->modelClass::all(), `

**Comment by sandervankasteel** [comment]
Can be closed, since this is fixed in pull request #43
