### ISSUE TITLE
Commit 47 @sandervankasteel , Ordina

### ISSUE THREAD

**Issue by SandervDoorn** [ronaldvandijk/colloquiumapp#48]
[Testreport Commit 47.docx](https://github.com/ronaldvandijk/colloquiumapp/files/585554/Testreport.Commit.47.docx)
Weergave
Voorgaande zaken zijn allemaal netjes opgelost, ik mis alleen nog de aanvraag knop.

_Staat nog niet in word doc_
Daarbij heb ik net opgemerkt: Als ik in de url een willekeurige andere id meegeef dan krijg ik alleen forbidden te zien. Misschien voor de nethheid de gebruiker terug te zetten naar my colloquia met een flashmelding dat hij daar niks te zoeken heeft?

**Comment by maantje** [comment]
@SandervDoorn Welke url gaat het hier om?

**Comment by SandervDoorn** [comment]
http://colloquiumapp/mycolloquia/edit/{{ID}}
