### ISSUE TITLE
Commit 46 @Jamie, Logica

### ISSUE THREAD

**Issue by SandervDoorn** [ronaldvandijk/colloquiumapp#49]
Weergave
Sidenav mag er nog uitgehaald worden. Misschien voor de netheid in het editscherm een knopje om terug te gaan naar rooms overview.
De applicatie wordt later zo gemaakt dat onder het admin dashboard een knop locations zit en daarachter de rooms, dus misschien in het overview een knopje terug naar locations dashboard maken.
[Testreport Commit 46.docx](https://github.com/ronaldvandijk/colloquiumapp/files/585548/Testreport.Commit.46.docx)

**Comment by ryanrio95** [comment]
Wordt opgelost

**Comment by SandervDoorn** [comment]
Hoor net dat Jamie er zelf ook aan werkt
