### ISSUE TITLE
404 Pagina styling

### ISSUE THREAD

**Issue by melledijkstra** [ronaldvandijk/colloquiumapp#52]
![image](https://cloud.githubusercontent.com/assets/8669499/20214826/d07b428a-a810-11e6-8447-ac779c59b201.png)

Misschien iets mee doen?

**Comment by SandervDoorn** [comment]
Neem dan ook meteen de 403 error mee, komt nog voor als je andermans colloquium wil editen via urlchange

**Comment by mishadokter** [comment]
Wil ik wel oppakken als niemand hier mee bezig is (geweest)

**Comment by sandervankasteel** [comment]
@mishadokter Klinkt als een leuke issue voor jou!

**Comment by mishadokter** [comment]
fixes #116
