### ISSUE TITLE
Titles van elke pagina

### ISSUE THREAD

**Issue by melledijkstra** [ronaldvandijk/colloquiumapp#53]
Er zijn nog veel pagina's (views) waar titles niet gezet zijn.
Zelf al een `@yield('title')` gemaakt in layout bestand zodat je alleen nog `@section('title', 'Page Title')` hoeft te gebruiken.

**Comment by Here2peer** [comment]
Ik pak deze wel op

**Comment by sandervankasteel** [comment]
Should be fixed in #105
