### ISSUE TITLE
Admin Dashboard link

### ISSUE THREAD

**Issue by SandervDoorn** [ronaldvandijk/colloquiumapp#57]
Of in het dropdown menu of in de navbar zelf moet even een linkje naar admin dashboard komen voor admins. Als ze nu linksboven klikken en dan op home kunnen ze niet meer dan admin dashboard (tenzij ze url aanpassen)

**Comment by ryanrio95** [comment]
Doe ik

**Comment by ryanrio95** [comment]
Opgelost in #81
