### ISSUE TITLE
Commit 34 @Maarten, IBM

### ISSUE THREAD

**Issue by SandervDoorn** [ronaldvandijk/colloquiumapp#70]
Routing
De route staat nu nog op admin/city, dit moet admin/cities worden.
Weergave
Ik krijg bij edit de volgende foutmelding:
 
Dit komt waarschijnlijk vanwege php7 tags, zorg aub dat het allemaal 5.6 compatible is. De kans is het grootst dat alles moet kunnen draaien op 5.6. Dit probleem kwam ik ook tegen bij locations, die moet ook nog opgelost worden. 
[Testreport Commit 34.docx](https://github.com/ronaldvandijk/colloquiumapp/files/589075/Testreport.Commit.34.docx)

**Comment by sandervankasteel** [comment]
Check, ga ik oppakken

**Comment by mro95** [comment]
Ben er mee bezig. PR soon!
