### ISSUE TITLE
Weet iemand nog iets moois voor het home scherm?

### ISSUE THREAD

**Issue by SandervDoorn** [ronaldvandijk/colloquiumapp#74]
Kom met ideeen, en als je idee over de top geniaal is pas hem dan toe

**Comment by ryanrio95** [comment]
Is een masonry grid met colloquia iets?

**Comment by melledijkstra** [comment]
Ik denk dat je gewoon als gebruiker naar de juiste controller moet worden gestuurd
- [ ] Planner -> colloquia overzicht om te approven
- [x] Admin -> admin panel
- [ ] User -> mijn colloquia?

**Comment by melledijkstra** [comment]
Is dit niet al gefixed? je wordt door gestuurd toch? dat had je gezegd in andere issue @ryanrio95

**Comment by melledijkstra** [comment]
@ryanrio95 Ik neem dit nu wel over
