### ISSUE TITLE
Locations, Buildings, Rooms in views koppeling laten zien (en in backend als dat nog niet is gedaan)

### ISSUE THREAD

**Issue by melledijkstra** [ronaldvandijk/colloquiumapp#94]
@Darkwater @MaartenOosting @Prolael 

Ik neem aan dat je bij de CRUD al de koppeling kan maken (met een dropdown).
Misschien in de view ook nog laten zien welke rooms gekoppeld zijn bij gebouwen.

**Comment by Prolael** [comment]
Done and merged, can be closed now.

**Comment by Prolael** [comment]
fixed:#94

**Comment by maantje** [comment]
Fixed in #133
